### ISSUE TITLE
The server sleeps to death

### ISSUE THREAD

**Issue by Brycey92** [Brycey92/Galaxy-Craft-Issues#57]
**Pack version**
1.0.5-1
SpongeForge 3616

**Describe the bug**
```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at java.lang.Thread.sleep(Native Method)
    at net.minecraft.server.MinecraftServer.redirect$addTickLimitWaitProfiler$bck000(MinecraftServer.java:5583)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:530)
    at java.lang.Thread.run(Unknown Source)
```

**To reproduce**
1. ???
2. Try to connect
3. The server times out

**Screenshots and crash reports**
[crash-2019-04-12_11.29.37-server.txt](https://github.com/Brycey92/Galaxy-Craft-Issues/files/3074001/crash-2019-04-12_11.29.37-server.txt)
[stall-2019-04-12_11.29.36.txt](https://github.com/Brycey92/Galaxy-Craft-Issues/files/3074002/stall-2019-04-12_11.29.36.txt)

**Computer information**
If you are encountering a crash, performance, or cosmetic issue, fill out this section. You may be asked for more information later.
Server computer:
- OS: Windows 10
- RAM Allocated: 4GB

**Comment by Brycey92** [comment]
doot on the Sponge Discord says that we should check things out with Spark or Timings.

**Comment by Brycey92** [comment]
I believe this is one and the same with #58, so I'm closing it.
